name: Deploy Dev Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'env/dev/**'
      - 'modules/**'

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  TF_VAR_RESOURCE_GROUP: ${{ secrets.TF_VAR_RESOURCE_GROUP }}
  TF_VAR_LOCATION: ${{ secrets.TF_VAR_LOCATION }}
  TF_VAR_ENVIRONMENT: ${{ secrets.TF_VAR_ENVIRONMENT }}
  TF_VAR_VNET_NAME: ${{ secrets.TF_VAR_VNET_NAME }}
  TF_VAR_SUBNET_NAME: ${{ secrets.TF_VAR_SUBNET_NAME }}
  TF_VAR_SECURITY_GROUP_NAME: ${{ secrets.TF_VAR_SECURITY_GROUP_NAME }}
  TF_VAR_IP_NAME: ${{ secrets.TF_VAR_IP_NAME }}
  TF_VAR_NIC_NAME: ${{ secrets.TF_VAR_NIC_NAME }}
  TF_VAR_SERVER_NAME: ${{ secrets.TF_VAR_SERVER_NAME }}
  TF_VAR_PORT: ${{ secrets.TF_VAR_PORT }}
  TF_VAR_MONGO_URI: ${{ secrets.TF_VAR_MONGO_URI }}
  TF_VAR_MONGO_INITDB_ROOT_USERNAME: ${{ secrets.TF_VAR_MONGO_INITDB_ROOT_USERNAME }}
  TF_VAR_MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.TF_VAR_MONGO_INITDB_ROOT_PASSWORD }}
  TF_VAR_EMAIL_SERVICE: ${{ secrets.TF_VAR_EMAIL_SERVICE }}
  TF_VAR_EMAIL_USER: ${{ secrets.TF_VAR_EMAIL_USER }}
  TF_VAR_EMAIL_PASS: ${{ secrets.TF_VAR_EMAIL_PASS }}
  TF_VAR_ADMIN_USERNAME: ${{ secrets.TF_VAR_ADMIN_USERNAME }}
  TF_VAR_SSH_KEY_PATH: "./keys/fashion-finder"

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH Keys
        run: |
          mkdir -p ./keys
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./keys/fashion-finder
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ./keys/fashion-finder.pub
          chmod 600 ./keys/fashion-finder
          chmod 644 ./keys/fashion-finder.pub

      - name: Install Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.2

      - name: Terraform Init
        run: terraform -chdir=env/dev init

      - name: Terraform Validate
        run: terraform -chdir=env/dev validate

      - name: Terraform Plan
        run: terraform -chdir=env/dev plan

      - name: Terraform Apply
        run: terraform -chdir=env/dev apply --auto-approve
